image: rambabusaravanan/firebase

stages:
  - deploy

cache:                  
  paths:                
    - node_modules/     

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - cd functions/
    - npm install
    - firebase use konux-server --token $FIREBASE_TOKEN
    - npm run deploy --only functions -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN